console.log("Hello World!");
console.log(typeof "Ranjit");
console.log(typeof 42);
console.log(typeof true);
console.log(typeof {});
console.log(typeof []);
console.log(typeof null);
console.log(typeof undefined);
console.log(typeof function () {});
console.log(typeof NaN);
console.log(typeof Infinity);
console.log(typeof -Infinity);
console.log(typeof new Date());
console.log(typeof new Error());
console.log(typeof new RegExp());
console.log(typeof new Boolean());
console.log(typeof new Number());
console.log(typeof new String());
console.log(typeof new Function());
console.log(typeof new Object());
console.log(typeof new Array());
console.log(typeof new Boolean());
console.log(typeof new Number());
console.log(typeof new String());
console.log(typeof new Function());
console.log(typeof new Object());
console.log(typeof new Array());
console.log(typeof new Boolean());
console.log(typeof new Number());
console.log(typeof new String());
console.log(typeof new Function());
console.log(typeof new Object());
console.log(typeof new Array());
console.log(typeof new Boolean());
